identifier: l5pci0n9s6s5xe2e
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /home/ade/Documents/project/my-blog
distFolder: ./dist/my-blog
outDir: /home/ade/Documents/project/my-blog/dist/static
handle404: ''
allowErrorCollect: false
